Fix from "2>&1" to "1>&2"

diff --git a/semi-automatic-text-editor b/semi-automatic-text-editor
--- a/semi-automatic-text-editor
+++ b/semi-automatic-text-editor
@@ -7,21 +7,21 @@ OFFSET=$4
 
 if [ ! -f $FILE ]
 then
-  echo "ERROR: \"$FILE\" dosen't exist!" 2>&1
+  echo "ERROR: \"$FILE\" dosen't exist!" 1>&2
   exit 1
 fi
 
 LINE=$(grep -nF "$LINE_INDICATOR" $FILE | cut -d ':' -f 1)
 if [ ! $LINE ]
 then
-  echo "ERROR: \"$LINE_INDICATOR\" line dosen't exist!" 2>&1
+  echo "ERROR: \"$LINE_INDICATOR\" line dosen't exist!" 1>&2
   exit 2
 fi
 
 grep -F "$INSERT_TEXT" $FILE > /dev/null
 if [ $? -eq 0 ]
 then
-  echo "ERROR: \"$INSERT_TEXT\" is already inserted!" 2>&1
+  echo "ERROR: \"$INSERT_TEXT\" is already inserted!" 1>&2
   exit 3
 fi
 
@@ -31,12 +31,12 @@ then
 fi
 if [ $LINE -lt 1 ]
 then
-  echo 'ERROR: LINE became negative or 0!' 2>&1
+  echo 'ERROR: LINE became negative or 0!' 1>&2
   exit 4
 fi
 if [ $LINE -gt $(cat $FILE | wc -l) ]
 then
-  echo "ERROR: LINE was over the number of lines of \"$FILE\"" 2>&1
+  echo "ERROR: LINE was over the number of lines of \"$FILE\"" 1>&2
   exit 4
 fi
 
